import 'package:flutter/material.dart';

void main() {
  runApp(const ToDoApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class ToDoApp extends StatelessWidget {
  const ToDoApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          AndroidLarge1(),
        ]),
      ),
    );
  }
}

class AndroidLarge1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 360,
          height: 800,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: Color(0xFFC7D6C7)),
          child: Stack(
            children: [
              Positioned(
                left: 11,
                top: 116,
                child: Container(
                  width: 337,
                  height: 568,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(20),
                    ),
                    shadows: [
                      BoxShadow(
                        color: Color(0x60021A03),
                        blurRadius: 20,
                        offset: Offset(5, 10),
                        spreadRadius: 0,
                      )
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 102,
                top: 164,
                child: Text(
                  'TO-DO LIST',
                  style: TextStyle(
                    color: Colors.black,
                    fontSize: 30,
                    fontFamily: 'Segoe UI',
                    fontWeight: FontWeight.w400,
                  ),
                ),
              ),
              Positioned(
                left: 30,
                top: 311,
                child: Container(
                  width: 300,
                  height: 40,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 300,
                          height: 40,
                          decoration: ShapeDecoration(
                            color: Color(0xFFE8E8E8),
                            shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(3)),
                            shadows: [
                              BoxShadow(
                                color: Color(0x3F000000),
                                blurRadius: 4,
                                offset: Offset(0, 4),
                                spreadRadius: 0,
                              )
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 276,
                        top: 6,
                        child: SizedBox(
                          width: 16,
                          height: 32,
                          child: Text(
                            'x',
                            style: TextStyle(
                              color: Colors.black,
                              fontSize: 20,
                              fontFamily: 'ABeeZee',
                              fontWeight: FontWeight.w400,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 15,
                        top: 11,
                        child: Text(
                          '투두2',
                          style: TextStyle(
                            color: Colors.black,
                            fontSize: 15,
                            fontFamily: 'Pretendard',
                            fontWeight: FontWeight.w200,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 30,
                top: 271,
                child: Container(
                  width: 300,
                  height: 40,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 300,
                          height: 40,
                          decoration: ShapeDecoration(
                            color: Color(0xFFE8E8E8),
                            shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(3)),
                            shadows: [
                              BoxShadow(
                                color: Color(0x3F000000),
                                blurRadius: 4,
                                offset: Offset(0, 4),
                                spreadRadius: 0,
                              )
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 276,
                        top: 6,
                        child: SizedBox(
                          width: 16,
                          height: 32,
                          child: Text(
                            'x',
                            style: TextStyle(
                              color: Colors.black,
                              fontSize: 20,
                              fontFamily: 'ABeeZee',
                              fontWeight: FontWeight.w400,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 15,
                        top: 11,
                        child: Text(
                          '투두1',
                          style: TextStyle(
                            color: Colors.black,
                            fontSize: 15,
                            fontFamily: 'Pretendard',
                            fontWeight: FontWeight.w200,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 224,
                top: 628,
                child: Container(
                  width: 102,
                  height: 36,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 102,
                          height: 36,
                          decoration: ShapeDecoration(
                            color: Color(0xFFB6D7B8),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(10),
                            ),
                            shadows: [
                              BoxShadow(
                                color: Color(0x59053207),
                                blurRadius: 4,
                                offset: Offset(4, 4),
                                spreadRadius: 0,
                              )
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 24,
                        top: 10,
                        child: Text(
                          '모두 삭제',
                          style: TextStyle(
                            color: Colors.black,
                            fontSize: 15,
                            fontFamily: 'Pretendard',
                            fontWeight: FontWeight.w500,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 30,
                top: 231,
                child: Container(
                  width: 300,
                  height: 40,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 300,
                          height: 40,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 260.10,
                                top: 0,
                                child: Container(
                                  width: 39.90,
                                  height: 40,
                                  decoration: ShapeDecoration(
                                    color: Colors.black,
                                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(2)),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 271.61,
                        top: 10.53,
                        child: Container(
                          width: 18.24,
                          height: 18.95,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 7.93,
                                top: 0,
                                child: Container(
                                  width: 3.17,
                                  height: 18.95,
                                  decoration: ShapeDecoration(
                                    color: Colors.white,
                                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(1)),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 7.41,
                                child: Container(
                                  width: 18.24,
                                  height: 3.30,
                                  decoration: ShapeDecoration(
                                    color: Colors.white,
                                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(1)),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 13.19,
                        top: 11.47,
                        child: SizedBox(
                          width: 39.53,
                          height: 18.95,
                          child: Text(
                            '텍스트',
                            style: TextStyle(
                              color: Colors.black,
                              fontSize: 15,
                              fontFamily: 'Pretendard',
                              fontWeight: FontWeight.w200,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}

